.gitignore, joi.d.ts, lib/decorators/pick-allowable-fields.ts, lib/decorators/validate.ts, lib/index.ts, lib/schema/activity.ts, lib/schema/beneficiary.ts, lib/schema/clinic.ts, lib/schema/notification.ts, lib/schema/provider.ts, package-lock.json, package.json, test/decorators.spec.ts, test/mocks/mock-schema.ts, test/validation.spec.ts
Adding and using `joi-browser` to fix an issue with IE
=> bug/QPPBSR-4166 Adding joi-browser pacakge

webpack.common.ts
Webpack UMD modules are broken currently: https://github.com/webpack/webpack/issues/6525
=> Fix broken umd module in node

lib/index.ts, lib/schema/activity.ts, package-lock.json, package.json
[QPPBSR-4156](https://jira.cms.gov/browse/QPPBSR-4156)
Updated activity schema
=> QPPBSR-4156 - updated activity schema

index.ts, lib/schema/index.ts, lib/schema/organization.ts, package-lock.json, test/organization.spec.ts
Adding organization schema to be used on both the bsr client and api.
=> QPPBSR-4161 Add organization schema

lib/schema/clinic.ts, lib/schema/provider.ts, package-lock.json, package.json
[QPPBSR-4160](https://jira.cms.gov/browse/QPPBSR-4160)
updated validation:
- clinic
- provider
=> updated clinic and provider schema

lib/schema/provider.ts, package-lock.json, package.json
added orgId to provider schema
=> added orgId to provider schema

index.ts, lib/regexes.ts, lib/schema/index.ts, lib/schema/organizationContact.ts, package-lock.json, package.json
[QPPBSR-4162](https://jira.cms.gov/browse/QPPBSR-4162)
- added organization contact
- add email regex
=> QPPBSR-4162 - added organization contact schema and email regex

package-lock.json, package.json
=> bump version to 0.4.0

package-lock.json, package.json
=> bump version to 0.5.0

index.ts, lib/schema/OrganizationAddress.ts, lib/schema/index.ts, lib/schema/notification.ts
[QPPBSR-4163](https://jira.cms.gov/browse/QPPBSR-4163)
- added OrganizationAddress 
- updated `NotificationMessageTypes` name
=> QPPBSR-4163 - added OrganizationAddress and updated `NotificationMessageTypes` name

package-lock.json, package.json
=> bump version to `0.6.0`

index.ts, lib/schema/index.ts
[QPPBSR-4163](https://jira.cms.gov/browse/QPPBSR-4163)
export `NotificationMessageTypes`
=> export `NotificationMessageTypes`

package-lock.json, package.json
=> version bump 0.7.0

index.ts, lib/schema/index.ts, lib/schema/registration.ts
[QPPBSR-4164](https://jira.cms.gov/browse/QPPBSR-4164)
added registration validation
=> QPPBSR-4164 - added registration validation

package-lock.json, package.json
=> bump version to 0.8.0

index.ts, lib/schema/beneficiary-measure.ts, lib/schema/index.ts, lib/schema/notification.ts, lib/schema/organization.ts, lib/schema/registration.ts
[QPPBSR-4157](https://jira.cms.gov/browse/QPPBSR-4157)
add beneficiary measure validation
=> QPPBSR-4157 - add beneficiary measure validation

package-lock.json, package.json
=> bump package version 0.9.0

package-lock.json, package.json
=> version bump to 0.9.1

index.ts, lib/schema/index.ts, lib/schema/submission.ts
[QPPBSR-4159](https://jira.cms.gov/browse/QPPBSR-4159)
added submission validation
=> QPPBSR-4159 - added submission validation

package-lock.json, package.json
=> bump package version - 0.10.0

package-lock.json, package.json
=> bumped version 0.10.1

lib/schema/clinic.ts, lib/schema/provider.ts
[QPPBSR-4160](https://jira.cms.gov/browse/QPPBSR-4160)
organizationId is required for clinic and provider
=> QPPBSR-4160 - organizationId is required for clinic and provider

package-lock.json, package.json
=> Bump version to 0103

lib/regexes.ts, lib/schema/clinic.ts, lib/schema/organization-address.ts
[QPPBSR-4483](https://jira.cms.gov/browse/QPPBSR-4483)
added state validation
=> QPPBSR-4483 - added state validation

package-lock.json, package.json
=> 0.11.0 - bump package version 

lib/schema/beneficiary-measure.ts
[QPPBSR-4580](https://jira.cms.gov/browse/QPPBSR-4580)
Added `s` to comment
=> QPPBSR-4580 - added `s` to comment

package-lock.json, package.json
=> 0.11.2 - bump version

package-lock.json, package.json
=> Version 0.11.3

lib/schema/beneficiary.ts, package-lock.json, package.json, test/beneficiary.spec.ts
Created an optional bene schema which can be used on bene updates. Adding a basic test for gender validation.
=> QPPBSR-4427: Bene schema updates

lib/schema/beneficiary.ts, lib/schema/measure.ts, package.json
Adding `.max(1000)` to comments fields.
=> bug/QPPBSR-4952: Comments field max length incorrect

lib/schema/beneficiary.complex.ts, lib/schema/submission.ts, package-lock.json, package.json, test/beneficiary-complex.spec.ts, test/submission.spec.ts
Updating bene complex for testing...
=> Updating bene complex schema

lib/schema/beneficiary.complex.ts, package-lock.json, package.json, test/beneficiary-complex.spec.ts
Fixing imports for beneficiary.complex
=> bug/QPPBSR-4957: Fixing imports for beneficiary.complex

package-lock.json, package.json
fix update package cryptiles to stable version to fix security vulnerability
=> QPPBSR-5034: update package cryptiles

lib/schema/clinic.ts, package-lock.json
[QPPBSR-5057](https://jira.cms.gov/browse/QPPBSR-5057)
removed `organizationId` from clinic
=> QPPBSR-5057 - remove org id from payload

package-lock.json
Updating package lock to fix security alert. `merge` is now `1.2.1` in `pacakge-lock.json`
=> QPPBSR-5263: Updating package-lock

lib/schema/measure-reset.ts, package.json, test/measure-reset.spec.ts
change measureSelections to measures
change clearBeneficiaryConfirmation to confirmation
make both fields required
=> change names of properties in reset measures validation

lib/schema/organization-contact.ts
allows blank phone extension in the organization contact form.
=> QPPBSR-5865: allow blank phone extension

lib/regexes.ts, lib/schema/beneficiary.ts, package.json, test/beneficiary.spec.ts
Updating regex for beneficiary first and last name so that periods are allowed.
=> QPPBSR-6019: Updating validation for bene names

lib/schema/organization-contact.ts, package.json, test/organization-contact.spec.ts
Updating first and last name validation for organization contacts.
=> QPPBSR-6038: Updating contact first and last name

lib/regexes.ts, package.json, test/regexes.spec.ts
=> Adding comma to address regex

lib/regexes.ts, package.json, test/regexes.spec.ts
Updating address regex with `&` and `%`
=> Updating address regex

lib/schema/registration.ts, package.json
update registration schema: replace groupReporting with bsrRegistered
linked API changes PR:  https://github.com/CMSgov/beneficiary-reporting-api/pull/2561
=> QPPBSR-6268:  change group_reporting to bsr_registered for organizations

package-lock.json, package.json, webpack.common.ts
This PR ensures that webpack transpiles required dependencies. If these files are not transpiled, then IE11 will not load the WI. The deduping will hoist redundant dependencies which prevents the regular expression from going crazy.
=> QPPBSR-6460 - webpack updates for IE11

lib/schema/beneficiary.ts, package-lock.json, package.json
allow only dates during current year for medicalNotQualifiedDate
=> QPPBSR-6464:  API | Out of Range Disqualification Date not rejected by API

lib/schema/beneficiary.ts
=> Quick fix for year change

lib/decorators/validate.ts, lib/index.ts, package-lock.json, package.json, test/activity.spec.ts, test/decorators.spec.ts, test/registration.spec.ts, test/validation.spec.ts
Adding test coverage reporting and increasing the coverage.
=> QPPBSR-7399: Adding test coverage and increasing it

lib/schema/beneficiary.ts, package-lock.json, package.json
update validation for medicalNotQualifiedDate for interim testing period before new year
=> QPPBSR-7156:  Update the beneficiary schema for "medicalNotQualifiedDate"

.github/workflows/pr-checker.yml, .github/workflows/publish.yml, README.md, package-lock.json, package.json
Updating dependencies and adding Github actions.
=> QPPBSR-7687 Setup GitHub actions & Dep updates

.github/CODEOWNERS, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/SUPPORT.md, LICENSE, README.md, SECURITY.md
https://jira.cms.gov/browse/QPPPM-1190 - As part of that ticket we are planning to open source a few client projects. In this PR, I am doing the prep work, by copy-pasting a few static MD files.
Please review and make any necessary edits and merge this PR into master branch.
=> QPPPM-1190 - Open sourcing efforts

.github/CODEOWNERS
=> Chore/Update Code Owners

.github/workflows/publish.yml
=> Remove broken publish steps

constants.ts, package-lock.json, package.json
Creates updates following README.md steps for measures json 2023
=> Update for WI measures json 2023

.github/CODEOWNERS, package-lock.json, package.json
Update class-validator to latest version to satisfy dependabot issue
> Also updated code owners
=> task/qppbsr-9879 Update class-validator to latest version

package-lock.json, package.json
=> task/qppbsr-10816 Update reflect-metadata
